# Generated by Django 5.0.1 on 2024-01-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productname', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='img')),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stockcount', models.IntegerField(default=0)),
                ('createdat', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
